<?php

namespace SanteBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use InvalidArgumentException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{



    public function findDqlSerieParametre($s)
    {
        $q=$this->getEntityManager()
            ->createQuery("select m FROM SanteBundle:Article  m WHERE m.titre=:titre
                             ")
            ->setParameter('titre',$s);
        return $q->getResult();

    }
}