<?php

namespace SanteBundle\Repository;

/**
 * blogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestBlogs($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->addOrderBy('b.createdAt', 'DESC')->setMaxResults(1);

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
            ->getResult();
    }
    public function findcategorie($s)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT  b FROM SanteBundle:blog b  WHERE b.titre=:titre")
            ->setParameter('titre','%'.$s.'%');
        return $q->getResult();
    }

}
