<?php

namespace SanteBundle\Repository;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function countActiveJobs()
    {
        return $this->createQueryBuilder('v')


            ->select('c.post')
->from('SanteBundle:categorie','c')
            ->addSelect('COUNT(x) AS categorie')
            ->leftJoin('c.post','x')
            ->groupBy('c.id')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();




    }
}