<?php

namespace SanteBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsForBlog($blog_Id)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.blog_Id = :blog_id')
            ->addOrderBy('c.createdAt')
            ->setParameter('blog_id', $blog_Id);
        return $qb->getQuery()
            ->getResult();
    }
}
