<?php

namespace SanteBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends EntityRepository
{
    public function findDemandeQB($id){
        $query=$this->createQueryBuilder('s');
        $query->where("s.user=:user")->setParameter('user',$id);

        return $query->getQuery()->getResult();
    }
}
