<?php

namespace SanteBundle\Repository;

/**
 * EstabmishmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstabmishmentRepository extends \Doctrine\ORM\EntityRepository
{
}
