<?php

namespace SanteBundle\Repository;

/**
 * EstabmishmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstabmishmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchByNom($s)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT p FROM SanteBundle:Estabmishment p WHERE p.nom LIKE :n")->setParameter('n', '%' . $s . '%');

        return $q->getResult();

    }
}
