services:
#    sante.example:
#        class: SanteBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  redirect.after.login:
      class: SanteBundle\Redirection\AfterLoginRedirection
      arguments: ["@router"]

# config/services.yaml

# ...
parameters:
    brochures_directory: '%kernel.project_dir%/public/uploads/images'